### ISSUE TITLE
List of failing imported entries

### ISSUE THREAD

**Issue by krainboltgreene** [gnocode/barcampnola5#17]
Here's a list of the entries that failed for one reason or another, usually no start_at date: https://gist.github.com/3135191

45 entries worked: http://nolavation-de-production.herokuapp.com/#15

There are also some in there that have bad `media` fields, aka not links but a series of links.

**Comment by joeellis** [comment]
Nice catches, I'll forward this over to Tritico to see if he can get a historian on board to fix up this data.

**Comment by joeellis** [comment]
Also, shall I go ahead and launch what's on master on the site as of now?

**Comment by krainboltgreene** [comment]
You'll need to run this before or after you push.

On Wed, Jul 18, 2012 at 8:16 AM, Joe Ellis
reply@reply.github.com
wrote:

> Also, shall I go ahead and launch what's on master on the site as of now?
> 
> ---
> 
> Reply to this email directly or view it on GitHub:
> https://github.com/gnocode/barcampnola5/issues/17#issuecomment-7068365

## 

Kurtis Rainbolt-Greene, Hacker
Difference Engineers, LLC
643 Magazine St. #102
New Orleans, LA 70130
